name: '⚙️ On pull request'

on:
  pull_request:
    branches:
      - alpha
      - beta

  repository_dispatch:
    types: [trigger-pr-build]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.client_payload.number || github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      ref: ${{ github.event.client_payload.ref || github.ref }}

  build:
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref || github.ref }}
          persist-credentials: false

      - uses: ./.github/actions/build
        id: build
        with:
          node-version: ${{ vars.NODE_VERSION }}
          php-version: ${{ vars.PHP_VERSION }}
          composer-flags: '--no-dev'

      - uses: myparcelnl/actions/pdk-prerelease-pr@v4
        with:
          image: ${{ steps.build.outputs.image }}
          pr-number: ${{ github.event.client_payload.number || github.event.pull_request.number }}
          source-hash: ${{ hashFiles('src/**/*', 'config/**/*', 'controllers/**/*', 'upgrade/**/*', 'myparcelnl.php', 'scoper.inc.php') }}
